#!/bin/bash
cd "$(dirname "$0")"

export WINEPREFIX=$(realpath ./lutris-GE-Proton7-35-x86_64/)
export WINEDEBUG=-all
export __GL_THREADED_OPTIMIZATIONS=1
WINE=$(realpath lutris-GE-Proton7-35-x86_64/bin/wine)

cat <<EOF
	 _   _            _               __  _____
	| | | | ___  _ __(_)_______  _ __ \ \/ /_ _|
	| |_| |/ _ \| '__| |_  / _ \| '_ \ \  / | |
	|  _  | (_) | |  | |/ / (_) | | | |/  \ | |
	|_| |_|\___/|_|  |_/___\___/|_| |_/_/\_\___|

EOF

# check if username/password configured yet
grep "\-\-user" HorizonXI/config/boot/horizonxi.ini 2>&1 > /dev/null

# if not configured, prompt user for login details
if [[ "$?" -ne 0 ]]; then
	echo -n "Username: "
	read USERNAME

	echo -n "Password: "
	read -s PASSWORD

	sed -i "s/^command.*$/command = --server betabox.horizonxi.com --user $USERNAME --pass $PASSWORD/g" HorizonXI/config/boot/horizonxi.ini
fi

# run HorizonXI
cd HorizonXI && $WINE Ashita-cli.exe horizonxi.ini 

